services:
  expo:
    image: node:20-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"